# BKG Biertypen {#app-bkgtabel}

Volgens het [BierKeurmeestersGilde](https://www.bierkeurmeestersgilde.nl){target="_blank"}

## Biertypenlijst {#biertype-tabel}

```{r bkg-tabel, echo=FALSE}
# Tabel met klassen als kolommen
bkg.klasse <- read_csv2("resources/bkg_biertypen.csv", show_col_types = FALSE) %>% 
	select(BIERTYPE, KLASSE)

kla <- bkg.klasse %>% filter(KLASSE == "A") %>% select(BIERTYPE) %>% rename("Klasse A" = BIERTYPE) %>% mutate(id = seq.int(nrow(.)))
klb <- bkg.klasse %>% filter(KLASSE == "B") %>% select(BIERTYPE) %>% rename("Klasse B" = BIERTYPE) %>% mutate(id = seq.int(nrow(.)))
klc <- bkg.klasse %>% filter(KLASSE == "C") %>% select(BIERTYPE) %>% rename("Klasse C" = BIERTYPE) %>% mutate(id = seq.int(nrow(.)))
kld <- bkg.klasse %>% filter(KLASSE == "D") %>% select(BIERTYPE) %>% rename("Klasse D" = BIERTYPE) %>% mutate(id = seq.int(nrow(.)))
lijst <- list(kla, klb, klc, kld)
bkg.tabel <- Reduce(function(x,y,...) merge(x,y, all=TRUE,...), lijst) %>% select(-id)

bkg.tabel %>%
	kbl(caption = "Tabel biertypen volgens BKG", position = "!ht") %>%
	kable_styling(latex_options = "scale_down", bootstrap_options = c("condensed", "responsive"), font_size = 12)
```

\newpage

## Dubbel kenmerken {#biertype-dubbel}

**Algemene kenmerken**

Een dubbel abdijbier of trappistenbier is een bovengistend typisch Belgisch, klassiek bier van 6,5 tot 7,5 Vol% alcohol.

**Uiterlijke kenmerken**

-  Kleur (donker) koper, roodbruin tot donkerbruin.
-  Helder.
-  Stabiele mousse schuimkraag.
-  Een dubbel heeft tamelijk veel koolzuur. 

**Geurassociaties**

-  Licht gebrand donker moutig, soms iets karamel, chocolade.
-  Matig zoetig (esters), fruitig (banaan, pruim, afhankelijk van de gistsoort).
-  Het hoparoma is hooguit zwak waarneembaar.
-  Complex, rijk moutige zoetheid, hints van chocolade, karamel en / of toast (maar nooit gebrande aroma's).
-  Matige fruitige esters (meestal inclusief rozijnen en pruimen, soms ook gedroogde kersen).
-  Kruidigheid en hogere alcoholen zijn soms herkenbaar.
-  Zwak hoparoma.

**Basissmaak**

-  Zoetig, bitterig.

**Smaak**

-  In evenwicht met de geur: zoetig tot mout bitterig, medium alcoholisch.
-  Soms zijn met kruiden toegevoegd, maar altijd in balans met moutigheid.
-  Complexe, medium-volle moutige zoetheid in de hoofdsmaak, matig droog uitlopend.
-  Complex samenspel van mout, esters, alcohol en fenolen (rozijnensmaken komen vaak voor, kruidnagel-achtige kruidigheid is mogelijk).
-  Hoofdsmaak is altijd in de richting van de mout.
-  Geen diacetyl.
-  Niet zo moutig als een bock.

**Body**

-  Medium
-  Doordrinkbaar.
-  Laag alcoholwarmend.

**Mondgevoel**

-  Iets plakkerig
-  Iets alcoholwarmend.
-  Koolzuurprikkeling is duidelijk aanwezig. 

**Nasmaak**

-  (licht) moutig
-  Iets bitter met vaak complexe fruitigheid en kruidigheid, afhankelijk van de gistsoort.

**Opmerkingen**

Een van de meest bekende speciaalbieren in Nederland en België. Minder karamel karakter dan bij een bockbier. 

**Technische kenemerken**

-  Begin SG: 1060-1072
-  SVG: 72-89%
-  Alcoholpercentage (ABV): 6,5-7,5%
-  Kleur: 40-100 EBC
-  Bitterheid: 20-30 EBU
-  Koolzuurgehalte: 5,0-7,0 gr/liter

## Tripel kenmerken {#biertype-tripel}

**Algemene kenmerken**

Een tripel is een bovengistend complex blond Belgisch biertype met 7,5 tot 9,5 Vol% alcohol.

**Uiterlijke kenmerken**

-  Blond tot goud.
-  Helder (tweeschijn is toegestaan).
-  Stevige, stabiele, romige schuimkraag.
-  Koolzuurgehalte is hoog.

**Geurassociaties**

-  Complex met kruidige, fruitige en (niet scherpe) alcoholische aroma's.
-  Duidelijk hoparoma, maar niet overheersend.
-  Licht mout karakter.
-  Fruitigheid loopt uiteen van citrusachtig, banaanachtig tot ander fruit, maar neigt nooit naar oplosmiddelachtige esters.
-  Kruidige fenolen afkomstig van de gist (kruidig, peperig, kruidnagelachtig) zijn waarneembaar, maar mogen niet overheersen.
-  Toevoeging van kruiden (vooral koriander) komt vaak voor, maar is niet vereist.
-  Mooie balans tussen gistkarakter, hop, mout en alcohol.
-  Niets mag overheersen.

**Basissmaak**

-  Zoetig, bitterig tot bitter.

**Smaak**

-  Samenspel van kruidige, fruitige en alcoholische smaken, ondersteund door een zachte moutigheid.
-  Hopbitterheid gemiddeld tot hoog, en goed in balans met de moutigheid en zoetheid. 

**Body**

Door het gebruik van tot 25% suiker heeft de tripel weinig body voor zijn hoge alcoholpercentage 

**Mondgevoel**

-  Soepel, alcoholwarmend en met veel koolzuurprikkeling.
-  Een beetje plakkerigheid is toegestaan.

**Nasmaak**

-  Esters, kruidigheid en moutigheid komen in de nasmaak voor.
-  Door het hoge koolzuurgehalte is de nasmaak droog tot licht zoetig en redelijk bitter.

**Opmerkingen**

-  Droger en meer koolzuur dan Barley Wine.
-  In vergelijking met Sterke Blonde moutiger
-  Nadruk ligt meer op fenolen dan op esters.

**Technische kenmerken**

-  Begin SG: 1075–1085
-  SVG: 73% – 90%
-  Alcoholpercentage (ABV): 7,5–9,5%
-  Kleur: 10–24 EBC
-  Bitterheid: 20–40 EBU
-  Koolzuurgehalte: 5,5–7,0 gr/ltr

## Weizen kenmerken {#biertype-weizen}

**Algemene kenmerken**

Een Weizen is een bovengistend blond Duits tarwebier (zonder toevoeging van kruiden) met 4,5 tot 5,9 Vol% alcohol.

**Uiterlijke kenmerken**

-  blond, geel tot amber
-  Tweeschijn tot troebel (afhankelijk van de manier van inschenken). De gefilterde kristal versie is briljant helder. De forse schuimkraag is romig, glasplakkend en houdt lang stand.
-  Het koolzuurgehalte is zeer hoog.

**Geurassociaties**

-  Typisch tarwearoma, dat omschreven kan worden als lichte tonen van brood en graan; weeïg en zoetzurig.
-  Karakteristiek aroma van kruiden en fruitige esters afkomstig van de gist. Kruidnagel en banaantjes (4VG) zijn vrijwel altijd aanwezig, daarnaast komt ook nootmuskaat voor.
-  Een hoparoma is vrijwel afwezig; het is subtiel en fijn van karakter indien wel aanwezig.
-  Geen diacetyl of DMS.
-  Vanille, esters of een lichte zuurheid van tarwe, zijn acceptabel en kunnen de complexiteit verhogen, maar mogen niet overheersen.

**Basissmaak**

-  De basissmaak is zoetig tot zoet, bitterig, soms zurig.

**Smaak**

-  Banaan en kruidnagel (weinig tot medium sterk, afkomstig van de gist) en aangenaam zoetig.
-  Soms is een zeer lichte vanille of ester smaak; maar nooit dominant, en in balans met de kruidnagel / banaan.
-  Zachte tarwesmaak (brood, graan).
-  Nauwelijks hopsmaak, hopbitterheid is (zeer) laag.
-  Vaak een zurige citrusachtige smaak (afkomstig van de gist en het hoge koolzuurgas gehalte en tarwe).
-  Het totale smaakpalet is rond en smaakvol.
-  Geen diacetyl en DMS.

**Body**

-  Dun tot medium, maar kan hoger lijken door de gist (in suspensie).

**Mondgevoel**

-  Plakkerig door de restsuikers.
-  Samentrekkend door het hoge koolzuurgehalte.
-  Los/romig door het tarwekarakter.
-  Levendig (licht mousserend) door het hoge koolzuurgasgehalte.

**Nasmaak**

-  Droog, ondanks de aanwezige restsuikers.

**Opmerkingen**

-  In tegenstelling tot Witbier worden geen kruiden toegevoegd en wordt gemoute tarwe gebruikt.

**Technische kenmerken**

-  Begin SG: 1046-1057
-  SVG: 78% – 84%
-  Alcoholpercentage (ABV): 4,5-5,9
-  Kleur: 6-25 EBC
-  Bitterheid: 10-20 EBU
-  Koolzuurgehalte: 5,5-7,5 gr/lit
