# Brouwsel-3 {#sec-brouwsel-3}

::: callout
## Doelstellingen

-   Je moet een recept voor een **Weizen** kunnen opstellen.
-   Je moet een *Weizen* volgens dit recept kunnen maken.
-   Je moet kunnen beoordelen of het brouwsel aan de eisen voldoet.
-   Je moet eventuele afwijkingen kunnen vaststellen.
-   Je leert de belangrijkste kenmerken van het te brouwen biertype.
:::

## Huiswerk

**Voorbereiding**

-   Bestudeer belangrijkste kenmerken van het te brouwen biertype In @sec-bkgtabel.
-   Zoek uit welke stappen in het maisch- en vergistingsproces voor een bepaalde smaak kunnen zorgen.
-   Maak een handmatige berekening van de hoeveelheid maisch- en spoelwater.
-   Stel een recept op en laat het beoordelen door de mentor.

## Draaiboek

-   Uitvoering bij de mentor of een van de teamleden.

## Evaluatie

-   Brouwproces bespreken.
-   Zoek een verklaring voor eventuele verschillen tussen de gemeten waarden en de beoogde waarden.
-   Gezamenlijk proeven, beoordelen of bier aan eisen/wensen voldoet.
-   Eventuele smaak- en geurafwijkingen bespreken.

## Testvragen

1.  Wat zijn de belangrijkste kenmerken van een Weizen?

2.  Wat is het verschil tussen een Duitse Weizen en een Belgisch witbier?

3.  Welke invloed heeft de vergistingstemperatuur van Weizenbier bij bijvoorbeeld Fermentis WB06 gist op de smaak?

4.  Hoe heb je de hoeveelheid brouw en spoelwater berekend voor de gebruikte installatie?

5.  Welke hopsoorten gebruikt men in het algemeen in Duitse weizenbieren?

6.  Wat houdt ferulerust in?
