# Brouwsel-4 {#brouwsel-4}

:::{.chapterintro}
**Doelstellingen**

-  Je kunt eisen/wensen voor een te maken bier formuleren.
-  Je kunt de belangrijkste kenmerken van het te brouwen biertype achterhalen.
-  Je kunt een recept voor dit bier opstellen.
-  Je kunt het recept in een brouwprogramma invoeren.
-  Je kunt het bier volgens het opgestelde recept brouwen.
-  Je kunt beoordelen of het gemaakte bier aan de eisen/wensen voldoet.
-  Je kunt eventuele afwijkingen vaststellen en aangeven waardoor deze zijn ontstaan.
:::

## Huiswerk {#b4-huiswerk}

**Voorbereiding**

-  Overleg welk bier je wilt maken. Dit kan een kloon van een bestaand bier zijn, maar je kunt ook de gewenste kenmerken van een "fantasiebier" formuleren.
-  Stel een recept voor het te maken bier samen en voer dit recept in een brouwprogramma in.

## Draaiboek {#b4-draaiboek}

-  Uitvoering bij de mentor of een van de teamleden.

## Evaluatie {#b4-evaluatie}

-  Presentatie van het bier en het recept.
-  Gezamenlijk proeven, beoordelen of bier aan doelstellingen voldoet.
