# Brouwsel-1

**Doelstellingen**

-  Een *Tripel* volgens een eenvoudig recept (1 maischstap) kunnen maken.
-  In grote lijnen de verschillende stappen van het brouwproces leren kennen.
-  Kennismaken met de apparatuur.
-  Leren reinigen en desinfecteren van de apparatuur.
-  Kennismaking met een aantal grondstoffen.

## Inleiding

In dit stadium wordt er vanuit gegaan dat je nog niet over eigen apparatuur beschikt. En het is ook niet de bedoeling dat je nu allerlei brouwapparatuur aanschaft. Verderop in deze cursus wordt daar extra aandacht aan besteed. Vandaar dat het eerste brouwsel op de apparatuur van de mentor wordt uitgevoerd. Tijdens het brouwen zal de mentor je bijstaan in het praktisch bierbrouwen en je alle stappen laten zien en/of laten uitvoeren.

> Mocht je wel over eigen apparatuur beschikken dan kan in overleg dit brouwsel ook hierop worden gemaakt in plaats van de apparatuur van de mentor.

Door het maken van het eerste brouwsel kom je veel van de voorafgaande theorie tegen en ga je deze in de praktijk toepassen. Vaak roept dat weer nieuwe vragen op. De mentor is hierbij jouw vraagbaak. Probeer ook zoveel mogelijk notities te maken om zo nadien alles rustig na te kunnen lezen. Je begrijpt de theorie beter door deze in de praktijk toe te passen. Leg ook een logboek aan waarin je alle waarnemingen opschrijft. Bij dit brouwsel horen ook een aantal vragen die je moet beantwoorden.

Sluit af met een evaluatie. Aan het eind van dit hoofdstuk zit een bijlage met daarin de belangrijkste kenmerken waar een tripel aan moet voldoen. Neem deze kenmerken mee bij de beoordeling van het gebrouwde bier.

\newpage
## Recept Tripel

Volume: 20 liter, Begin SG: $\pm1080$, Eind SG: $\pm1018$

**Grondstoffen**

-  *Mout*
   +  Pilsmout (3 EBC): 6600 gram
   +  Ambermout (50 EBC): 200 gram
-  *Hop*
   +  Challenger (6,5% alfazuur): 32 gram
-  *Kruiden*
   +  Koriander (gekneusd): 10 gram
   +  Paradijszaad: 10 gram
-  *Gist*
   +  Fermentis Safbrew T-58
-  *Water*
   +  Maischwater: ca. 20 liter (hangt van apparatuur af)
   +  Spoelwater: hoeveelheid samen met mentor bepalen (hangt van meerdere factoren af)

**Proces**

-  *Maischen*
   +  Maischdikte ligt tussen 3,5-5,5 liter/kg mout
   +  Gelijkblijvende infusie op $66^oC$ gedurende 60 minuten (Let op pH maisch)
   +  Uitmaischen op $78^oC$ gedurende 5 minuten
-  *Spoelen*
   +  Spoel langzaam, mag 40-60 minuten duren. Langzamer spoelen verhoogt het rendement.
   +  Stop met spoelen als SG in de uitloop tussen 1010-1020 ligt (mits je dit kunt meten)
-  *Koken*
   +  Kooktijd op $100^oC$ gedurende 60 minuten
   +  Hop 60 minuten koken
   +  Kruiden laatste 10 minuten meekoken
-  *Gisting*
   +  Hydrateer eventueel de gist.
-  *Bottelen*
   +  Bottelen als vergisting gestopt is (3 dagen geen activiteit, SG meten)
   +  6-8 gram suiker per liter bottel suiker.
   +  Gebruik eventueel bottelgist, bijvoorbeeld F2 van Fermentis.

\newpage

## Draaiboek

Bij dit eerste brouwsel krijg je nog een gedetailleerd draaiboek. Bij de volgende brouwsels moet je daar zelf om denken.

1.	 Lees het recept goed door.
1.	 Controleer de ingrediënten.
1.	 Schroot de mout.
1.	 Zet de brouwmaterialen klaar en steriliseer (eventueel reinigen) de brouwspullen die in contact komen met de wort.
1.	 Meet de hoeveelheid maischwater af en verwarm deze op tot de begintemperatuur.
1.	 Stort de mout in het brouwwater. Roer de maisch om zo klonters te voorkomen. Waak voor zuurstofinslag, dus niet te hard roeren.
1.	 Probeer de temperatuur op de doeltemperatuur te houden en niet meer dan $\pm 1^oC$ af te laten wijken.
1.	 Tijdens de amylaserust kan je de maischpan eventueel in een hooikist zetten of warmhouden in een deken. Anders zo nu en dan bijverwarmen.
1.	 Meet na 10 minuten de pH waarde. Optimum ongeveer 5,4 pH. Eventueel aanzuren met melkzuur of fosforzuur.
1.	 Tijdens verwarmen roeren om aanbranden te voorkomen. Wat valt je tijdens het brouwproces op  als je handmatig roert?
1.	 Voer na 20 en 60 minuten de jodiumtest uit. Wat is het verschil in kleur tussen beide tijdstippen? En wat zegt je dat?
1.	 Meet aan het begin en aan het eind van de $66^oC$-stap het SG van de maisch. 
1.	 Uitmaischen gebeurt op $78^oC$.
1.	 Meet aan het begin en aan het eind van de $78^oC$ stap het SG van de maisch.
1.	 Zorg dat je het filter (indien nodig) hebt gesteriliseerd.
1.  Zorg dat het spoelwater op temperatuur is ($80^oC$) en de juiste pH heeft (5,2), dus eventueel aanzuren.
1.  Filter langzaam. Kort voordat het filterbed begint droog gaat vallen begin je met het spoelen.
1.  Meet op gezette tijdstippen het SG aan de uitloop van het filter.
1.  Meet het volume en het SG van de wort aan het begin van het koken.
1.	 Meet volume wort voor en na kookproces. Hoeveel wort is er verdampt.
1.	 Zorg dat je de ingrediënten nodig tijdens het kookproces bij de hand hebt.
1.	 Start na het filteren het kookproces en zorg voor een rollende kook.
1.	 Voeg tijdens het  kookproces op de juiste tijdstippen de ingrediënten toe.
1.	 Zorg voor het einde van het koken dat je koeler, gistvat, en slangen hebt gereinigd en gedesinfecteerd. Ook het filter wanneer je deze gebruikt.
1.	 Na het koken koel de wort zo snel mogelijk af naar $23^oC$.
1.	 Begin ondertussen met het reinigen van de spullen die je niet meer nodig hebt.
1.	 Hydreer de korrelgist ongeveer een half uur voordat je de gist ent (toevoegt)
1.  Breng de afgekoelde wort over naar het gistvat (eventueel met gebruik van een filter).
1.	 Schud de inhoud van het gistvat flink zodat er lucht in de wort komt.
1.  Voeg de gist toe. Dat kan als suspensie wanneer je gehydrateerd hebt of je kunt het direct op de wort strooien.
1.	 Laat de wort temperatuur gecontroleerd vergisten.
1.	 Controleer regelmatig de activiteit van de vergisting door of te meten of de activiteit van het waterslot in de gaten te houden.
1.	 Je kan eventueel na de hoofdvergisting (ca. 3-5 dagen) het jongbier overhevelen naar een ander schoon en gedesinfecteerd gistvat. Dit is optioneel.
1.	 Stel vast wanneer de vergisting is afgelopen.
1.  Zet desgewenst het jongbier een paar dagen koud weg voor een eerste klaring.
1.  Bereken de hoeveelheid bottelsuiker (5-8 gram/liter) en los deze op in iets kokend water.
1.  Wanneer je bottelgist (bijvoorbeeld fermentis Safbrew F-2) gaat gebruiken, hydrateer dan de hoeveelheid (ca. 0,5 gram/liter) in wat jong bier.
1.	 Voeg de bottelsuiker onder roeren toe aan het jongbier.
1.  Wanneeer je bottelgist (bijvoorbeeld Fermentis Safale F-2) gaat gebruiken, hydrateer dan ca. 1 gram per 20-25 liter in wat jong bier en voeg deze daarna toe aan het te bottelen bier.
1.  Zorg dat de bierflessen goed gereinigd en gedesinfecteerd zijn.
1.	 Vul de flessen af tot 1-2 cm onder de flessenhals en sluit de flesjes.
1.	 Laat de flesjes bier nagisten door deze minimaal 2 weken op $18^oC$ a $25^oC$ weg te zetten.
1.	 Label je flesjes of krat/vat.
1.  Zet de flesjes koel en donker weg.
1.	 Reinig de gebruikte apparatuur.
1.  Proef regelmatig het bier en noteer je waarnemingen.

## Vragen

1.	 Hoe noemt men de eenstapsmaisch methode ook wel?
1.	 Wat was de temperatuur van het water voor de moutstort en wat is de temperatuur van de wort direct erna? Waarom is er een verschil?
1.	 Hoe heb je de hoeveelheid spoelwater bepaald?
1.  Wat was de verandering van het SG tijdens de $66^oC$-maischstap? Verklaar deze verandering.
1.  Hoeveel water is er tijdens het koken verdampt?
1.  Hoeveel liter wort is er in het gistvat gegaan?
1.	 Wat was het begin SG in het gist vat?
1.  Wat was het eind SG in het gistvat?
1.  Hoe heb je vastgesteld wanneer de vergisting is afgelopen?
1.  Hoeveel bottelsuiker heb je toegevoegd en hoe je dat berekend?
1.  Hoeveel liter bier is er netto gebotteld?
1.	 Bereken het alcoholpercentage (ABV %) van het bier met de formule $ABV\% = (Begin SG - Eind SG) \times 0,136 + 0,4$
1.  Door de schijnbare vergistingsgraad uit te rekenen krijg je een idee hoeveel procent van de aanwezige suikers is omgezet. Bereken de schijnbare vergistingsgraad (SVG) met de formule $SVG = \frac{Begin SG - Eind SG}{Begin SG -1000} \times 100$

## Evaluatie

-  Brouwproces bespreken. Ga samen met de mentor na wat er goed en fout ging en wat de eventuele invloed hiervan is op het bier.
-  Gezamenlijk proeven, beoordelen of bier aan doelstellingen voldoet.
-  Eventuele smaak- en geurafwijkingen bespreken.

## Kenmerken Tripel

Volgens het [BierKeurmeestersGilde](https://www.bierkeurmeestersgilde.nl){target="_blank"}

**Algemene kenmerken**

Een tripel is een bovengistend complex blond Belgisch biertype met 7,5 tot 9,5 Vol% alcohol.

**Uiterlijke kenmerken**

-  Blond tot goud.
-  Helder (tweeschijn is toegestaan).
-  Stevige, stabiele, romige schuimkraag.
-  Koolzuurgehalte is hoog.

**Geurassociaties**

-  Complex met kruidige, fruitige en (niet scherpe) alcoholische aroma's.
-  Duidelijk hoparoma, maar niet overheersend.
-  Licht mout karakter.
-  Fruitigheid loopt uiteen van citrusachtig, banaanachtig tot ander fruit, maar neigt nooit naar oplosmiddelachtige esters.
-  Kruidige fenolen afkomstig van de gist (kruidig, peperig, kruidnagelachtig) zijn waarneembaar, maar mogen niet overheersen.
-  Toevoeging van kruiden (vooral koriander) komt vaak voor, maar is niet vereist.
-  Mooie balans tussen gistkarakter, hop, mout en alcohol.
-  Niets mag overheersen.

**Basissmaak**

-  Zoetig, bitterig tot bitter.

**Smaak**

-  Samenspel van kruidige, fruitige en alcoholische smaken, ondersteund door een zachte moutigheid.
-  Hopbitterheid gemiddeld tot hoog, en goed in balans met de moutigheid en zoetheid. 

**Body**

Door het gebruik van tot 25% suiker heeft de tripel weinig body voor zijn hoge alcoholpercentage 

**Mondgevoel**

-  Soepel, alcoholwarmend en met veel koolzuurprikkeling.
-  Een beetje plakkerigheid is toegestaan.

**Nasmaak**

-  Esters, kruidigheid en moutigheid komen in de nasmaak voor.
-  Door het hoge koolzuurgehalte is de nasmaak droog tot licht zoetig en redelijk bitter.

**Opmerkingen**

-  Droger en meer koolzuur dan Barley Wine.
-  In vergelijking met Sterke Blonde moutiger
-  Nadruk ligt meer op fenolen dan op esters.

**Technische kenmerken**

-  Begin SG: 1075–1085
-  SVG: 73% – 90%
-  Alcoholpercentage (ABV): 7,5–9,5%
-  Kleur: 10–24 EBC
-  Bitterheid: 20–40 EBU
-  Koolzuurgehalte: 5,5–7,0 gr/ltr
