# Brouwsel-3 {#brouwsel-3}

**Doelstellingen**

-  Je moet een recept voor een **Weizen** kunnen opstellen.
-  Je moet een *Weizen* volgens dit recept kunnen maken.
-  Je moet kunnen beoordelen of het brouwsel aan de eisen voldoet.
-  Je moet eventuele afwijkingen kunnen vaststellen.
-  Je leert de belangrijkste kenmerken van het te brouwen biertype.

**Voorbereiding (huiswerk)**

-  In bijlage \@ref(bijlage-biertypen) staan de belangrijkste kenmerken van het te brouwen biertype. Neem deze goed door.
-  Zoek uit welke stappen in het maisch- en vergistingsproces voor een bepaalde smaak kunnen zorgen.
-  Maak een handmatige berekening van de hoeveelheid maisch- en spoelwater.

**Uitvoering**

-  Uitvoering bij de mentor of een van de teamleden.

**Evaluatie**

-  Brouwproces bespreken.
-  Gezamenlijk proeven, beoordelen of bier aan doelstellingen voldoet.
-  Eventuele smaak- en geurafwijkingen bespreken.

## Huiswerk:

-  Zelf maken van een recept voor brouwsel-3 waarbij vooraf aangegeven wordt welke kenmerken het bier moet hebben, zoals kleur, alkohol, bitterheid, moutigheid, zoetigheid, enz.
-  Beoordeling door mentor.
-  Na een proeverij evalueren in hoeverre het brouwsel voldoet aan de vooraf gestelde eisen/wensen. Kwamen de meetwaarden overeen met de beoogde waarden. Verklaring voor eventuele verschillen.
