# Brouwproces - Basis

Doel: Begrijpen uit welke stappen het brouwproces bestaat, zonder al te diep op deze stappen in te gaan.

## Het proces in grote lijnen

In grote lijnen gaat het maken van bier als volgt:

1.  Het zetmeel in de mout moet worden omgezet in suikers.
1.  De ontstane suikers moeten door de gist omgezet worden in alkohol.

Dit ziet er eenvoudig uit. In principe kun je een bier maken in een (soep)pan in de keuken. Maar het is toch wel een complex proces. Het gaat niet zomaar vanzelf. En om een goed bier te maken moet je wel wat meer weten over de afzonderlijke processen.

## recept

Om een bepaald bier te maken heb je een recept nodig. Hierin staat onder andere welke grondstoffen je nodig hebt en hoeveel daarvan.

In het begin krijg je zo'n recept vaak van anderen, maar als snel zul je een eigen recept willen opstellen. Daarover later meer.

## Mouten

Binnen in de gerstkorrel zit zetmeel. Om het zetmeel in suikers om te zetten heb je de hulp van enzymen (een bepaald soort eiwitten) nodig. Echter in onbehandelde brouwgerst zitten deze enzymen niet. Vandaar dat onbehandelde brouwgerst niet geschikt is voor het brouwen van bier.

Om brouwgerst geschikt te maken, wordt het eerst gemout. Hierbij wordt de gerst eerst geweekt in water. En als de gerst zich helemaal hiermee heeft volgezogen wordt het op een warme vloer uitgestort. Na enige tijd gaat de korrel ontkiemen en vormt dan enzymen. Zodra de gerst is ontkiemd, worden de graankorrels bij hoge temperatuur gedroogd om het kiemproces te stoppen. Het resultaat heet **mout**. Hoe hoger de temperatuur bij het drogen is, des te donkerder de mout. De kleur van de mout bepaalt ook de kleur van het bier. En ook heeft de mout een belangrijke invloed op de uiteindelijke smaak van het bier.

Dit mouten gebeurt vindt plaats in **mouterijen** en doe je niet zelf. Afhankelijk van het soort bier dat je wilt maken schaf je bepaalde mouten aan. te doen. Een bekende mouterij in Nederland is The Swaen[@Swaen2019] in Kloosterzande.

## Afwegen ingrediënten

Als voorbereiding op het echte brouwen ga je alle ingrediënten eerst afwegen. Dat kan met een goede keukenweegschaal.

## Schroten

Hele moutkorrels kun je niet gebruiken. De moutkorrels moeten eerst opengebroken worden. Dat heet **schroten**. Met behulp van een schrootmolen worden de korrels geplet zodat er een breuk in de korrel ontstaat waardoor het water bij het binnenste (het zetmeel) kan komen. Verwar het niet met fijnmalen. De kafjes die om fe korrel zitten moeten zoveel mogelijk heel blijven. Deze kafjes helpen je later bij het filteren van het bier. Als je het mout te fijn schroot krijg je later filterproblemen. Ook komen er dan meer ongewenste stoffen vrij uit de kaf van het mout, hetgeen de kwaliteit van het bier niet ten goede komt. Omdat geschrote mout snel in kwaliteit achteruit gaat kun je het beste de mout zelf schroten.

Er zijn verschillende soorten schrootmolens voor de hobbybrouwer. Zie verder bij \@ref(apparatuur).

## Maischen

In deze stap moet het zetmeel in de mout door enzymen omgezet worden in suikers. Daartoe wordt in een ketel (maischpan) het geschrote mout toegevoegd aan een bepaalde hoeveelheid water. Dit wordt **inmaischen** genoemd. Het ontstane mengsel wordt **beslag** of ook wel **maisch** genoemd.

In het recept staat hoeveel **maischwater** je nodig hebt. De temperatuur waarbij je de geschrote mout toevoegt aan het water wordt de **inmaischtemperatuur** genoemd. Ook dit staat in het recept.

De verschillende enzymen werken het beste bij bepaalde temperaturen. Daartoe wordt het beslag onder rustig roeren opgewarmd tot de temperatuur waarbij de enzymen het beste werken. En die temperatuur wordt dan een tijdje aan gehouden, het beslag krijgt een **rust**. Daarna wordt er opgewarmd tot een volgende temperatuur waarbij andere enzymen het beste werken en krijgt het beslag ook een bepaalde rusttijd. De verschillende temperaturen waarbij gerust wordt heet **maischschema**. In deel 2 van deze cursus wordt verder ingegaan op de achtergronden van dit **maischen**.

Aan het eind van het maischen heb je een mengsel van een vloeistof, waarin de suikers zijn opgelost, met vaste stoffen, zoals kafjes en korrelresten van de mout. In de volgende stap wordt dit van elkaar gescheiden.

## Filteren

het mengsel aan het eind van het maischproces wordt gefilterd. Je krijgt dan

-  **wort**, een heldere zoete vloeistof
-  **(bier)bostel**, de vaste bestanddelen die overblijven.

Voor de bierbereiding heb je de bostel niet nodig. Het wordt vooral als veevoer gebruikt, maar ook voor bijvoorbeeld bierbrood.

Om deze scheiding uit te voeren heb je een filter nodig. Hobbybrouwers gebruiken hiervoor meestal een **hevelfilter**, al dan niet zelf gemaakt. Zie hiervoor bij \@ref(apparatuur). De kafjes en korrelresten vormen hierbij het filterbed. Vandaar dat je niet te fijn mag schroten, want dan werkt het filterbed niet goed. De wort laat je in de kookketel (kookpan) lopen.

## Spoelen

In het filterbed zitten nog veel suikers. Om die ook in de wort te krijgen wordt het filterbed met warm water (maximaal 78^o C) langzaam en voorzichtig doorgespoeld. In het recept is weer terug te vinden hoeveel **spoelwater** je nodig hebt.

## Koken

Nu gaat de wort gekookt worden. Tijdens het koken wordt de hop toegevoegd. In het recept staat weer hoe lang de **kooktijd** (minimaal een uur) is en hoeveel gram van welke hop hoe lang moet meekoken. Koken is om meerdere redenen erg belangrijk.

Tijdens het koken

-  vlokken eiwitten uit, vooral in het begin. Deze kun je het beste met een schuimspaan afscheppen.
-  lossen bitterstoffen uit de hop op. Deze **bitterhop** moet minstens een uur koken en zorgt voor de kenmerkende bittere smaak van bier.
-  komen aromastoffen uit de hop in het bier. Deze **aromahop** kook je minder lang mee.
-  verdampen ongewenste vluchtige stoffen.
-  verdampt water, waardoor de concentratie van suiker toeneemt.
-  ontstaat er een steriele vloeistof.

*Na het koken moet je zeer hygiënisch te werk gaan!*

## Koelen

Na het koken van de wort moet deze afgekoeld worden tot de temperatuur waarbij vergist gaat worden. De thuisbrouwer gebruikt hier meestal een **spiraalkoeler** of een **platenkoeler** voor. Zie verder bij \@ref(apparatuur).

## Filteren

De afgekoelde vloeistof moet nu naar het **gistvat**. Echter er zitten nog hopresten en eiwitvlokken in de wort die liever niet mee wilt nemen. Gelukkig zakken deze meestal naar de bodem. En sommige brouwers maken een zogenaamde **whirlpool** waardoor deze restanten nog beter bezinken.

Wanneer de ongewenste stoffen voldoende bezonken zijn kun je de vloeistof over hevelen naar het gistvat. Er blijft dan nog een klein beetje in de kookketel achter.

## Gist toevoegen

Eenmaal in het gistvat kan de gist toegevoegd worden. In het recept staat weer welke gist, hoeveel daarvan en of er een zogenaamde **giststarter** gemaakt moet worden. Ook de temperatuur waarbij vergist moet worden vind je in het recept. In deel 3 wordt hier verder op ingegaan.

Tijdens de vergisting mag er geen lucht (zuurstof) bij de vloeistof komen. Vandaar dat het gistvat vaak met een **waterslot** of op een andere manier wordt afgesloten.

Meestal begint de vergisting binnen een halve tot hele dag. Er ontstaat koolzuurgas in de vorm van schuim en belletjes die via het waterslot ontsnappen. Bij bovengistende bieren duurt de **hoofdgisting** meestal zo'n 2-5 dagen. Daarna neemt de snelheid van vergisting af en krijg je de periode van de **navergisting**. Sommige brouwers hevelen daartoe de vloeistof over naar een nieuw vat. Anderen doent dat juist weer niet omdat door het overhevelen de kans op een besmetting toeneemt.

## Lageren

Wanneer de vloeistof is uitvergist kan het gelagerd worden. Het **jongbier** kan dan rijpen en helder worden. Dit **klaren**  gebeurt het beste bij een lage temperatuur, indien mogelijk iets boven 0^o C. Afhankelijk van het soort bier kan deze periode wel 2-8 weken duren.

De meeste thuisbrouwers slaan deze periode over. Wat velen wel doen is het gistvat aan het eind nog zo'n 3 dagen in de koelkast zetten. Hierbij wordt het bier ook grotendeels geklaard.

## Bottelen

Als laatste moet het bier afgevuld worden. Zeker in het begin zal dat in flessen zijn. Later mogelijk ook in vaatjes.

Om voldoende koolzuur in het flessenbier te krijgen moet er een **navergisting** in de fles plaatsvinden. Dat kan door nog wat suiker, zogenaamde **bottelsuiker**, aan het bier toe te voegen. De hoeveelheid hiervan is weer in het recept terug te vinden. Deze bottelsuiker wordt in een beetje water opgelost, aan de kook gebracht en daarna aan het jongbier toegevoegd. dan kan het vullen van de flessen beginnen.
