# (PART) Deel 1 {-}
# Inleiding

**Doelstellingen**

-  Aangeven wat de cursist na afloop van de cursus mag verwachten.
-  Uitleg hoe de cursus is opgezet.

## Verwachtingen cursus

Na afloop van de cursus wordt het volgende van je verwacht.

-  Je weet hoe bier gemaakt wordt en je kunt dat ook zelf.
-  Je weet de achtergronden van de processen.
-  Je kunt zelf een recept opstellen.
-  Je weet een bier te classificeren.
-  Je weet hoe je bier moet proeven en beoordelen.
-  Je kent een aantal brouwfouten en weet hoe die te vermijden.

## Opzet cursus

Het cursusboek is concentrisch opgezet. Dat wil zeggen: eenvoudig beginnen met een steeds verdere uitbreiding en verdieping. Daartoe is de cursus en het cursusboek opgedeeld in 4 delen.

Samen met een mentor wordt in elk deel een brouwsel gemaakt. Je maakt dus in totaal 4 brouwsels. Ook deze brouwsels gaan van een eenvoudig recept naar een steeds complexer recept. In het begin krijg je een kant en klaar recept aangeleverd, aan het eind zul je er zelf een moeten maken. Het is de bedoeling dat je tijdens het maken van deze vier brouwsels steeds meer zelfstandigheid laat zien.

Daarnaast leer je hoe een bier te proeven en te beoordelen, ook wel *degusteren* genoemd.

-  Deel 1:
   +  Basisprincipes van het brouwproces.
   +  Minimale apparatuur.
   +  *Brouwsel-1*: eenvoudig, volgens verstrekt recept.
-  Deel 2:
   +  Nadruk op mout en maischen.
   +  *Brouwsel-2*: meerdere maischstappen, volgens verstrekt recept.
-  Deel 3:
   +  Nadruk op hop, vergisting, en recepten.
   +  *Brouwsel-3*: voorgeschreven biertype, eigen recept.
-  Deel 4:
   +  Nadruk op fouten, afwijkingen en beoordelen.
   +  Brouwsoftware.
   +  *Brouwsel-4*: een eigen geformuleerd bier, eigen recept.


