# Logboek {#logboek}

::: {.intro data-latex=""}

-  Je moet weten waarom het belangrijk is om een logboek bij te houden.
-  Je moet weten welke informatie in het logboek moet komen.

:::

## Waarom een logboek?

Het is belangrijk dat je bij het brouwen zoveel mogelijk gegevens over het brouwproces en meetwaarden vast legt. Ook waarnemingen, metingen en acties na de brouwdatum leg je in het logboek vast. Evenals proef- en keurgegevens. Hierdoor is het gemakkelijker om achteraf na te kunnen gaan wat je gedaan hebt en eventuele fouten op te sporen. Daarnaast kun je met deze gegevens ook een goed uitgevallen bier nog eens opnieuw maken.

## Inhoud logboek

De volgende onderdelen dienen in een logboek vermeld te worden:

-  Datums van brouwen, vergisten, bottelen, proeven, ...
-  Het gebruikte recept.
-  Het gevolgde brouwproces en hoe je de verschillende stappen hebt uitgevoerd.
-  Meetwaarden: volumes, temperaturen, pH's, SG's, Brix, ...
-  Verloop van de vergisting.
-  Bottelen.
-  Beoordeling van het bier.
-  Eigenlijk alles wat van belang kan zijn om op een later tijdstip na te gaan hoe een en ander verlopen is.

Sommigen gebruiken als logboek een notitieboek of een multomap, anderen houden de gegevens bij in een Word- of Excelbestand. En ook de meeste brouwsoftware biedt mogelijkheden om notities te maken bij een brouwsel. In welke vorm je een logboek bijhoudt is niet belangrijk, als je het maar doet. 
