# Over bier

## Geschiedenis

Een korte geschiedenis over het ontstaan van bier en wat bier eigenlijk is, [@BiersectorNederland2019].

### Wat is bier?

De drank die we in Nederland bier mogen noemen, is vastgelegd in de Bierverordening. Onder bier wordt hierin verstaan: ‘de drank verkregen na alcoholische gisting van wort, hoofdzakelijk bereid uit zetmeel- en suikerhoudende grondstoffen, hop - eventueel in verwerkte vorm- en brouwwater, op voorwaarde dat tenminste 60% van de wort afkomstig is van gerste- en/ of tarwemout.’ Om ‘bier’ te mogen heten, moet de drank dus in ieder geval bestaan uit water, gerst- en/of tarwemout, hop en water: allemaal natuurlijke ingrediënten. Bier kan dan ook met recht een natuurproduct genoemd worden.

Bier is de oudste alcoholhoudende drank ter wereld. Het wordt wereldwijd gedronken en staat op de derde plaats op de wereldranglijst van meest populaire dranken, na water en thee. Het ambacht van het bier brouwen ontstond al vele duizenden jaren geleden. Hoewel traditionele brouwmethoden nu nog steeds gebruikt worden, hebben we inmiddels het vakmanschap van toen gecombineerd met de moderne hedendaagse technologie.

### Geschiedenis

In de vroege Middeleeuwen was het brouwen van bier een huishoudelijke bezigheid, voorbehouden aan vrouwen. Om in hun levensonderhoud te voorzien, brouwden ook kloosterlingen (monniken en nonnen) verschillende bieren. In de tijd van Karel de Grote (rond 800) ontstonden grotere brouwerijen om de hoeveelheden bier te brouwen die nodig waren voor het hof of voor grotere huishoudens. Naast het thuis brouwen kwam ook het zogenaamde koopbrouwen door ambachtslieden in gebruik. Met de koopbrouwer was de commerciële bierbrouwerij geboren.

In de Middeleeuwen werd veel bier gedronken. Met gemak dronk iedere man, vrouw of kind wel 300 liter bier per jaar. Het bier dat de Middeleeuwer dagelijks dronk lijkt overigens niet op het bier dat we nu drinken. Het bevatte nauwelijks alcohol en smaakte waarschijnlijk vrij zuur. Men dronk bier als alternatief voor water dat toen gehaald werd uit sloten en grachten. Dit water bevatte veel bacteriën en leidde tot ziektes.

Het aantal bierbrouwerijen steeg in deze tijd gestaag. Steden met meer dan 100 brouwerijen waren geen uitzondering. Bekende brouwsteden uit die tijd zijn Amersfoort, Delft, Haarlem en Gouda. De bierbrouwers, die zich verenigden in gilden, waren vaak de machtigste kooplieden in de stad of de streek. Men beweert zelfs dat de overwinning op de Spanjaarden tijdens de Tachtigjarige Oorlog grotendeels met accijns op bier gefinancierd is.

### De introductie van hop

In de talrijke kloosters en abdijen werd de kunst van het bierbrouwen steeds verder verfijnd. Waarschijnlijk ontstond ook daar het idee om gruit (verschillende kruiden) in bier te vervangen door hop. Bier met hop was smakelijker. Bovendien bederft het bier door hop minder snel. Voor commerciële bierbrouwers gaf dit veel voordelen. Het werd nu bijvoorbeeld mogelijk om bier zonder kwaliteitsverlies te exporteren. Vanaf de vijftiende eeuw werd vrijwel uitsluitend nog maar hoppebier gebrouwen.

### Het ontstaan van een nieuw biersoort: pils

In Bohemen (Tsjechie) werd in die tijd een nieuw biersoort uitgevonden; een bier dat we nu kennen onder de naam pils. Om pils te kunnen brouwen moet het bij lage temperaturen vergisten en lageren. Dat kon in ons land pas effectief toen rond 1880 de koelmachine werd uitgevonden. Tot die tijd moest de brouwer in de winter staven ijs uit sloten, rivieren en meren hakken om het bier ook in de zomer koel te houden. Pils werd razend snel het meest gedronken biersoort in Nederland. In de jaren zeventig van de vorige eeuw werd er zelfs nog bijna alleen maar pils gebrouwen in Nederland. Bier en pils waren synoniem geworden.

### Speciaalbier

Halverwege de jaren tachtig vond een nieuwe ontwikkeling plaats. Anders smakende bieren, de zogenaamde speciaalbieren uit België werden populair en het duurde niet lang voordat bestaande en nieuwe kleine brouwerijen ook in Nederland begonnen met het brouwen van speciaalbier. Soms worden oude recepten nieuw leven ingeblazen, vaak ook verzint een brouwer een creatief nieuw recept.

## Ingrediënten

Bier is een natuurlijk product dat wordt gemaakt van water, graan, hop en gist.

### Water

Bier bestaat voor meer dan 90% uit water. Zuiver water is dan ook een belangrijk ingrediënt om goed bier te brouwen. Veel brouwerijen zuiveren het water dat zij gebruiken nog eens extra zodat deze altijd de juiste, speciale samenstelling heeft. Afhankelijk van de biersoort mag dit water sporen van mineralen bevatten.

### Graan

Graan vormt een belangrijk ingrediënt voor de smaak, alcohol en kleur van het bier. Voor de meeste bieren gebruikt de brouwer **brouwgerst**. Dit is een graan dat speciaal wordt geteeld voor het brouwen van bier. Brouwgerst bevat veel zetmeel en een specifieke hoeveelheid eiwitten (tussen 9,5% en 10,5%). Brouwgerst wordt eerst **gemout** voordat het geschikt is om mee te brouwen. Ook andere granen zijn geschikt om bier mee te brouwen. Tarwe(mout) vormt bijvoorbeeld een belangrijk bestanddeel van witbier. Maar ook met haver, mais en zelfs rijst wordt wel eens bier gebrouwen.

### Hop

Hop is een klimplant die van nature in Nederland voorkomt. De brouwer gebruikt de bloemetjes van de vrouwelijke hopplant om bier de kenmerkende bittere smaak te geven. Daarnaast geeft hop stevigheid aan het bierschuim en is het een natuurlijk conserveringsmiddel. Naast hop kan de brouwer er voor kiezen om ook andere smaakmakers in het bier te gebruiken. Denk hierbij aan kruiden als anijs, koriander of zoethout. Ook vruchten, al dan niet bewerkt, worden in sommige bieren gebruikt. De bekendste voorbeelden zijn sinaasappelschil in sommige witbieren of kersen in kriekbier.

### Gist

Gist is onmisbaar voor het maken van bier. Gist is een eencellige schimmelsoort die in staat is om suikers om te zetten in alcohol en koolzuurgas. Daarnaast is het ook een belangrijke smaakmaker. Elke giststam (gistcultuur) heeft een eigen aroma en smaak en zorgt in combinatie met de andere ingrediënten voor een uniek bier. Als de gist in het bier achterblijft is het bier troebel. Voor heldere bieren is de gist voor het afvullen gefiltreerd.

Afhankelijk van de vergistingsmethode heb je drie soorten bieren:

-  **Bovengistende bieren**, Trappistenbier, Stout, Porter
-  **Ondergistende bieren**, voorbeelden: Pilsener, Bockbier
-  **Spontaan gistende bieren**, voorbeelden: geuzebier, lambiekbier

