# Recepten

**Doelstellingen**

-  Weten hoe je aan een goed recept kunt komen.
-  Een bestaand recept kunnen aanpassen aan de eigen installatie.
-  Zelf een eenvoudig recept kunnen opstellen.

## Inleiding

Hoe kom je tot een recept voor een goed en succesvol bier? In het begin is dat niet eenvoudig en gebruik je snel een recept van een ander. Zeker wanneer je een volgens dit recept gebrouwen bier geproefd hebt en lekker vindt, kan dit vertrouwen in het recept geven. Soms moet je dan nog wat aan de hoeveelheden veranderen om het recept aan je eigen installatie aan te passen, maar daarna ben je snel klaar en daar is niets mis mee. Ook zijn er veel boeken en websites met recepten, teveel om op te noemen.

Waar je als beginnend brouwer veel aan kunt hebben zijn de [Bewezen Recepten](https://www.hobbybrouwen.nl/forum/index.php?topic=4459.0) op het forum van Hobbybrouwen. Dit zijn recepten van bieren die ooit een prijs gewonnen hebben op een wedstrijd.

Het wordt wat anders wanneer je een bepaald bier wilt klonen of een bier wilt brouwen dat aan bepaalde kenmerken voldoet. Dan moet je het opstellen van een recept wat systematischer aanpakken. En om een goed recept te kunnen samenstellen moet je wat weten over de kenmerken van de verschillende grondstoffen en over de processen die plaatsvinden tijdens het maischen, koken en vergisten.

## Aanpassen bestaand recept

Wanneer je volgens een bestaand recept van iemand anders wilt brouwen, kan het zijn dat je dit recept wat aan moet passen. Vaak moet het bottelvolume aangepast worden aan het volume voor je eigen installatie. Hierdoor moeten ook de hoeveelheden mout, water, hop  en soms gist worden aangepast. Gebruik van brouwsoftware is ook hier gemakkelijk omdat deze vaak over schalingsmogelijkheden beschikken en alle hoeveelheden aanpassen aan het nieuwe bottelvolume.

Het kan ook zijn dat een van de ingrediënten wilt wijzigen, bijvoorbeeld omdat een bepaald ingrediënt niet meer voorradig of te koop is. Op internet zijn hiervoor substitutielijsten te vinden.

## Nieuw recept

Voor de ontwikkeling van een recept is het raadzaam om dit gestructureerd te doen. Het standaardboek op dit gebied is Designing Great Beers [@danielsDesigningGreatBeers1996]. Zijn zes stappenplan ziet er als volgt uit.

1.  Bepaal hoeveel en welk bier je wilt maken en wat de kenmerken van dit bier moeten zijn.
    +  bottelvolume
    +  gisttype (bovengistend, ondergistend, wilde gisting)
    +  begin SG
    +  bitterheid (IBU)
    +  kleur (EBC)
    +  gewenste moutkenmerken
    +  gewenste hopkenmerken
    +  gewenste smaak- en geurkenmerken
    +  gewenste speciale ingrediënten (kruiden, ...)
2.  Bepaal welke moutsoorten je wilt gebruiken en bereken de hoeveelheden hiervan.
    +  basismout(en)
    +  speciale mout(en)
    +  maischschema
3.  Bereken de hoeveelheden water en ga na of je het water moet behandelen.
    +  waterprofiel
    +  eventuele behandeling (pH, brouwzouten)
4.  Bepaal welke hopsoorten je wilt gebruiken en bereken de hoeveelheden.
    +  gewenste hoparoma en smaak
    +  tijdstip(en) en tijdsduur hopgiften
    +  dryhopping gewenst?
5.  Bepaal welke gist je wilt gebruiken en stel een plan voor de vergisting op.
    +  gistsoort
    +  hoeveelheid gist
    +  giststarter nodig?
    +  vergistingstemperatuur
    +  diacetylrust nodig?
    +  lagering nodig?
6.  Bepaal welke punten van belang zijn voor de afhandeling aan het eind.
    +  klaring (natuurlijk, met hulpmiddelen)
    +  verpakken
       *  bottelen (bottelsuiker, bottelgist, hergistingstemperatuur en -tijd)
       *  fust (koolzuurdruk en verzadigingsmethode)

Een handige gids is de Biertypengids van Derek Walsh [@walshBiertypengids2002]. In deze gids vind je een overzicht van biertypen met uitgebreide technische specificaties, bijzonderheden en receptaanwijzingen voor elk biertype. Helaas is deze biertypengids niet meer te koop. De [BKG Biertypenlijst](https://www.bierkeurmeestersgilde.nl/biertypenlijst) is hieruit voortgekomen. Hierin worden ook de biertypen beschreven met hun kenmerken, maar geen recepturen. De lijst is vooral belangrijk wanneer je met jouw gebrouwde bier wilt meedoen aan een wedstrijd.

Een nuttig artikel dat je kan helpen bij het samenstellen van recepten is [Samenstellen bierrecepten](https://www.hobbybrouwen.nl/artikel/samenrec.html) Van Jacques Bertens, op de site van Hobbybrouwen. Je start hier met de keuze van een biertype. Wanneer het gewenste biertype niet in de tabel staat kies je een type dat er het dichtst bij in de buurt komt.

### Voorbeeld: Weizen

Je wilt een recept samenstellen voor het maken van 20 liter Duitse Weizen. Om wat speelruimte te hebben hou je voor de technische specificaties de gemiddelde waarden in de BKG biertypenlijst aan.

-  Begin SG: 1052
-  Alcoholpercentage (ABV): 5,3%
-  Kleur: 15 EBC
-  Bitterheid: 12 EBU
-  Kooktijd: 75 min

Alleereerst de moutsamenstelling. Een Duitze Weizen moet uit minstens 70% tarwemout bestaan. besloten wordt voor een verdeling van 65% tarwemout en 35% pilsmout.

\@ref(vb2-mout) is berekend dat je dan 3111 gram tarwemout en 1702 gram pilsmout nodig hebt. Totaal dus 4813 gram.

Als Hop wordt gekozen voor een Zuid-Duitse hoppe: Hallertau perle met 7,9% alfazuur als bitterhop en Tettnager 3,5% als aromahop. In \@ref(vb2-ebu) is berekend dat je 12 gram van deze hop dodig hebt.

Als gist wordt gekozen voor een korrelgist welke geschikt is voor tarwebieren. fermentis SafAle WB-06 is een geschikte gist.

Voor het maiscschema, koken en vergisting worden de aanwijzingen in het boek van Derek Walsh [@walshBiertypengids2002] opgevolgd.

## Huiswerk:

-  Zelf maken van een recept voor brouwsel-3 waarbij vooraf aangegeven wordt welke kenmerken het bier moet hebben, zoals kleur, alkohol, bitterheid, moutigheid, zoetigheid, enz.
-  Beoordeling door mentor.
-  Na een proeverij evalueren in hoeverre het brouwsel voldoet aan de vooraf gestelde eisen/wensen. Kwamen de meetwaarden overeen met de beoogde waarden. Verklaring voor eventuele verschillen.
