# Voorwoord {.unnumbered}

De cursus is opgezet om samen met anderen, bij voorkeur binnen een club/gilde, te leren wat de kenmerken van bier zijn en hoe het brouwen van bier in zijn werk gaat en dat ook in de praktijk te brengen. Voor verwijzingen naar de websites van een aantal bierbrouwgildes zie bijlage \@ref(app-gildes). Informeer naar de mogelijkheid tot het volgen van een cursus. Eventueel kun je de cursus ook individueel doorwerken. Maar de praktische onderdelen (brouwen en proeven) lenen zich er meer voor om onder begeleiding van een ervaren hobbybrouwer uit te voeren. 

De cursus is concentrisch opgezet. Dat wil zeggen: eenvoudig beginnen met een steeds verdere uitbreiding en verdieping. Daartoe is de cursus opgedeeld in 4 delen. Elk deel eindigt met het maken van een brouwsel. Dit brouwsel kun je het beste samen met een ervaren hobbybrouwer uitvoeren, die als mentor kan fungeren. Je maakt in deze cursus dus 4 brouwsels. Ook deze brouwsels gaan van een eenvoudig recept naar een steeds complexer recept. In het begin krijg je een kant en klaar recept aangeleverd, aan het eind zul je deze zelf moeten maken. Het is de bedoeling dat je tijdens het maken van deze vier brouwsels steeds meer zelfstandigheid laat zien.

Daarnaast leer je in praktijkbijeenkomsten hoe je een bier moet proeven en beoordelen, ook wel *degusteren* genoemd.

-  Deel 1:
   +  Basisprincipes van het brouwproces.
   +  Minimale apparatuur.
   +  *Brouwsel-1*: eenvoudig, volgens verstrekt recept.
-  Deel 2:
   +  Nadruk op mout, suikers en maischen.
   +  *Brouwsel-2*: meerdere maischstappen, volgens verstrekt recept.
-  Deel 3:
   +  Nadruk op hop, vergisting, rekenen en recepten.
   +  *Brouwsel-3*: voorgeschreven biertype, eigen recept.
-  Deel 4:
   +  Nadruk op fouten, afwijkingen en beoordelen.
   +  Brouwsoftware.
   +  *Brouwsel-4*: een eigen geformuleerd bier, eigen recept.

**Verwachtingen cursus**

Na het doorwerken van de cursus wordt het volgende van je verwacht.

-  Je weet hoe bier gemaakt wordt en je kunt dat ook zelf.
-  Je weet de achtergronden van de processen.
-  Je kunt zelf een recept opstellen.
-  Je weet een bier te classificeren.
-  Je weet hoe je bier moet proeven en beoordelen.
-  Je kent een aantal brouwfouten en weet hoe die te vermijden.

